### PR TITLE
add two more levels #309

### PR DESCRIPTION
**Pull request by sroertgen**
Added two more levels as discussed in #309 

@LasseMempel would you mind testing out?

cc @acka47

### CODE REVIEW

**Comment by LasseMempel** [comment]
It seems to be supporting 6 levels at the moment, if I am not mistaken we were targeting at least 7?
I attached the resulting hierarchy up to "Röntgenuntersuchung" and a section of the turtle file with two concepts containing "Röntgenuntersuchung" as skos:broader.

Screenshot 2024-09-04 102212
Screenshot 2024-09-04 101803

The repository is: https://github.com/LasseMempel/RestSkos-pages
You can find the turtle file here:  https://github.com/LasseMempel/RestSkos-pages/blob/main/skosifyCSV/fixedData.ttl

Thank you for your work!

**Comment by sroertgen** [comment]
Thanks for testing. Seems like we need yet another level. Added it and tested with your vocab. I now have two narrower concepts:
grafik

**Review by acka47 — APPROVED** [review]
+1

**Comment by sroertgen** [comment]
> Sorry, I forgot this PR. We definitely need to restart some regular meeting to go through the Kanban board...
> 
> I also tested this PR with the vocab from https://github.com/LasseMempel/RestSkos-pages/blob/main/skosifyCSV/fixedData.ttl. The build works and the result is at https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/leiza.de/thesaurus.html. All levels seem to be covered, thus, this can be deployed.

yes, we should do that. or maybe do it as a community call and we use metadata.community to announce it?

**Pull request merged**
