### PR TITLE
Move gatsby modules to devDependencies

### PR DESCRIPTION
**Pull request by dr0i**
- update the gatsby-plugin-sharp to fix critical issue

See https://github.com/skohub-io/skohub.io/issues/16.

### CODE REVIEW

**Comment by dr0i** [comment]
Assigning @acka47 for functional review.

**Comment by acka47** [comment]
I pushed the changes to `dev` branch for functional review on the test system.

**Comment by dr0i** [comment]
So I guess the functional review is ok ? My own functional review is looking ok.

**Comment by acka47** [comment]
> So I guess the functional review is ok ?

Yes, +1

**Review by acka47 — APPROVED** [review]

**Comment by dr0i** [comment]
Deployed, closed.

**Pull request merged**
