### PR TITLE
281 notes

### PR DESCRIPTION
**Pull request by sroertgen**
Adds the following documentation properties:

- `skos:changeNote`
- `skos:editorialNote`
- `skos:historyNote`

All note attributes properties (including `skos:note` and `skos:scopeNote`) now allow multiple entries.

Tests were added for all note attributes.

cc @carlschuurbiers

### CODE REVIEW

**Comment by sroertgen** [comment]
Can't assign @carlschuurbiers as reviewer. But feel free to test this out as well

**Comment by sroertgen** [comment]
@acka47 this PR was merged in dev. You can use the test environment for testing this PR.

**Comment by acka47** [comment]
> @acka47 this PR was merged in dev. You can use the test environment for testing this PR.

Is the test system somehow broken? I get this error: https://test.skohub.io/build/?id=b669982f-4d49-4f60-a776-bb0e59ccb386

The webhook was delivered from this repo fte rchanges in the master branch: https://github.com/acka47/testing-skohub-vocabs

**Comment by acka47** [comment]
Test system seems to work but I get an error I do not understand quickly, see https://test.skohub.io/build?id=d673121d-d4d5-432c-a3df-15bc9a66095f

**Review by acka47 — APPROVED** [review]
+1 Works as expected

**Pull request merged**
