### PR TITLE
Add concept scheme to embedded concepts #295

### PR DESCRIPTION
**Pull request by sroertgen**
The concept scheme was not yet added to the embedded concepts for hash uris. If visiting a hash uri concept scheme directly this resulted in a crash.

Will deploy this to test system after #293 #294 are merged.

### CODE REVIEW

**Comment by sroertgen** [comment]
How to test:

- use a hash uri concept scheme
- build the vocab
- visit the concept scheme

if it's not crashing it's working.

**Comment by acka47** [comment]
It's not crashing but it also looks different than the non `#scheme` URL. Compare:

* https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/nwbib.de/subjects.html
* https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/nwbib.de/subjects.html#scheme

In the second case there is another box around the concept scheme description:

image

**Comment by sroertgen** [comment]
@acka47 Good catch, like always!

I aligned the design and pushed the changes to the test container. Please test again.

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
