### PR TITLE
258 shape

### PR DESCRIPTION
**Pull request by sroertgen**
SKOS files are now validated against the SkoHub shape (https://github.com/skohub-io/shapes/blob/main/skohub.shacl.ttl).

If the files **violate** the shape the build will stop.

If the files hit **warnings**, the build will continue, but the error message will still be printed to the console.

### CODE REVIEW

**Comment by sroertgen** [comment]
@acka47 I suggest trying out by pulling this branch and testing against valid and invalid SKOS turtle files with `npm run build`

**Comment by acka47** [comment]
This seems to work fine. However, the error messages are not easy to parse for the human eye. Would it be possible to provide the path to the file where an error is located? This might already help.

Or also provide the `dct:title` (in English) of the vocab where the error occured, `a la:

> info Node, where the error occured: LRMI Interact Type Vocabulary <http://purl.org/dcx/lrmi-vocabs/interactivityType/>

**Comment by acka47** [comment]
It would also be good if violations could be highlighted somehow in the validation list. It would make things easier, if you have a lot of warnings and only one violation.

**Comment by sroertgen** [comment]
Violations are now indicated with a red Error message. 
Violations and Warnings are now differentiated.
The filepath is also provided.

`dct:title` is not yet available when I'm testing, since I want to fail as early as possible, avoiding possible other bugs rising from invalid SKOS files.

**Comment by sroertgen** [comment]
@acka47 Please review the requested changes.

**Review by acka47 — APPROVED** [review]
+1 I think this is fine for now. We can always improve it when more user feedback comes in.

**Pull request merged**
