### PR TITLE
220 update packages

### PR DESCRIPTION
**Pull request by sroertgen**
Updating and upgrading packages as well as migrating from enzyme to react-testing-library for testing, as enzyme is no longer maintained.

### CODE REVIEW

**Comment by sroertgen** [comment]
Note: This currently not on dev for testing. Since this has major changes, we should test it separately from the other features currently on dev.

**Review by acka47 — APPROVED** [review]
I checked out the branch and did 
1. `$ nvm use 14`
2. `$ npm ci`
3. `$ cp .env.example .env`
4. copy examples into `/data` folder
5. `$ npm run develop`

I didn't get error messages and everything seems to work fine. Thus,+1

**Comment by sroertgen** [comment]
I hope it was `nvm use 18`, otherwise we might have a problem :smiley:

**Comment by acka47** [comment]
> I hope it was `nvm use 18`, otherwise we might have a problem :smiley: 

Yes, it works with 18, just tried it out. (Updated my comment accordingly)

**Pull request merged**
