### PR TITLE
263 vocabs without apache

### LINKED ISSUE #263: Enhance usability/accessibility of concepts
**Situation**
- Currently the docker image `skohub/skohub-vocabs-docker:latest` provides language-based html files, no general "index.html" (as found in [skohub-docker-vocabs#7](https://github.com/skohub-io/skohub-docker-vocabs/issues/7))

**Drawbacks**
- Dealing with concept ids looking like URIs might confuse users, if they are used to accessing them with the expectation of reaching meaningful content. Although the main purpose is unique identification, it might not be from a user's perspective

**Non-working Example**
- The concept id "https://w3id.org/comein/vocabs/DigCompEdu/3.2" leads to "You just hit a route that doesn't exist... the sadness."

**Working Example**
- Skohub.io seems to integrate a redirect pattern based on the working example concept id "http://w3id.org/kim/kmk-vocabs/digitalisierungsbezogene-kompetenzen/F427CBE5-3444-405B-B3ED-31392C5AD548" which leads to the concept item

**How to deal with the drawback**
- Maybe generation of index.html or htaccess rules redirecting to existing language files by default/existance?

### LINKED ISSUE #270: Cypress GitHub Actions Fails, but works locally

### LINKED ISSUE #283: Link to ConceptScheme keeps displayed when going from index to a ConceptScheme and then going back
@carlschuurbiers pointed out:

 if you go from the index page, where als Concep tSchemes are displayed to a Concept Scheme and then go back, the header still contains the Concept Scheme.

This should be fixed and a test added.

### PR DESCRIPTION
**Pull request by sroertgen**
SkoHub Vocabs is now no longer dependent on an Apache Webserver to be delivered through.
The language is now chosen through the browser language.

All End-2-End tests and unit/integration tests are going through.

I deployed to dev and you can use the test webhook to test: https://test.skohub.io/sroertgen/test-vocabs/heads/main/

Benefits of this:
- Independence of web server
- GitHub Pages can now find the index page (no pointing to a specific language required)
- Build size is reduced (e.g. from 45MB and 1074 pages to 25MB for 368 pages for the test data sets)

Open question:
- Should the language be choosable via query parameter or similar? If so how, exactly?

Before merge:

- [x] set up redirects of `de.html` pages to `html` (maybe with adding the language param, depending on open question)
- [ ] update documentation of skohub-vocabs-docker after PR

Fixes #263 
Fixes #270
Fixes #283

### CODE REVIEW

**Comment by acka47** [comment]
See #280 for a problem introduced on with this PR on the test system.

**Comment by acka47** [comment]
I did some functional review, Overall this looks very mature, but I noticed one thing:

- #283 seems only to be fixed partly, I tested it on your test examples and on my newly built test repo at https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/ :
  -  One incorrect behaviour is fixed: When I click on a concept and then click on the SkoHub Vocabs Header image, the concept scheme title is now gone.
  - But:  When I click on a concept and then click the back button in the browser, the concept scheme title is still displayed as heading of the concept scheme list.

Otherwise this looks good. Wrt the direct language links, I thin we should have them. At least fpr bug fixing in SkoHub or by a vocab's editors it will be useful to directly link to a page in a specific language. For me it would be ok to implement this by a query parameter, e.g. `?lang=de`. And of course this should be set in the URL bar latest when I select a specific language. Probably it should already be set when the display ist set to the language requested by the browser or – if this is not available – when displaying the default language.

**Comment by sroertgen** [comment]
Parsing for an URL parameter `lang=` is implemented, see e.g.

<https://test.skohub.io/sroertgen/test-vocabs/heads/main/?lang=nl>
<https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/kim/hcrt/scheme.html?lang=uk>

If language from URL parameter does not exist, a default language is chosen:

<https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/kim/hcrt/scheme.html?lang=bla>

Also the use of the browsers "Go Back" function should now remove the concept scheme info in the header.

Assigning @acka47 for testing.

**Comment by acka47** [comment]
I build a new version on test with my testing repo to have a look at this: https://test.skohub.io/build/?id=58f2d04b-e0b7-4dc9-8cfd-97e13c088d3d

> Parsing for an URL parameter lang= is implemented, see e.g.
> 
> https://test.skohub.io/sroertgen/test-vocabs/heads/main/?lang=nl

Yes, it works. See also https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/?lang=en

> https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/kim/hcrt/scheme.html?lang=uk

Hmm, this does not work for me: https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/assessment.html&lang=de Am I doing something wrong?

> If language from URL parameter does not exist, a default language is chosen:
> https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/kim/hcrt/scheme.html?lang=bla

Works here: https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/?lang=foo
but not here: https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/assessment.html&lang=foo

> Also the use of the browsers "Go Back" function should now remove the concept scheme info in the header.

Yes, this works now.

I have noticed that the URL does not change when switching the language. I think we have already discussed this. Did we settle on not representing the current language state anymore at all in the URL?

**Comment by acka47** [comment]
My bad, it works with question mark instead of  ampersand .

**Comment by acka47** [comment]
So, this looks good. +1

> I have noticed that the URL does not change when switching the language. I think we have already discussed this. Did we settle on not representing the current language state anymore at all in the URL?

This is ok. We will mainly use direct links to a language for debugging and now about how to create them. Others won't need this.

**Review by acka47 — APPROVED** [review]

**Comment by sroertgen** [comment]
Assigning @Phu2 for setting up redirects:

If someone comes with `...index.de.html` or `...scheme.de.html` it needs to be redirected to `index.html?lang?en` or `scheme.html?lang=de` etc

**Comment by Phu2** [comment]
Added

```
        # Redirect from ...filename.LANGCODE.html to ...filename.html?lang=LANGCODE
        RewriteRule ^(.+)\.([a-z]{2})\.html$ $1.html?lang=$2 [L,R=301]
```

to Apache vhost config `test.skohub.io.conf` and reloaded.

**Comment by sroertgen** [comment]
With https://github.com/skohub-io/skohub-webhook/pull/20 we tested to rebuild vocabularies on the test environment and it seems to work.

The redirect is also configured, so https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/kim/hcrt/application.de.html will redirect to https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/kim/hcrt/application.html?lang=de

Next steps will be:

- [ ] Merge https://github.com/skohub-io/skohub-webhook/pull/20
- [ ] Merge this PR (so the docker image gets build)
- [ ] Rebuild the vocabularies on prod
- [ ] Add rewrite rule to prod instance

What do you think @Phu2 @acka47 ?

**Comment by Phu2** [comment]
+1

**Comment by acka47** [comment]
Sounds good to me.

Last step:

- [ ] Write a blog post and make people aware about this breaking change who host their own instances (WLO, IQB, FWU).

**Comment by sroertgen** [comment]
Fallback if it would not work for any reason:

- Mount the backup dist directory
- change the docker tag in skohub-webhook to `with-apache`
- remove the apache rewrite rule

**Pull request merged**
