### PR TITLE
Add skos:related inverses

### LINKED ISSUE #123: Infer inverse of skos:related statements
From https://github.com/skohub-io/skohub-vocabs/issues/105#issuecomment-720959194:

> As skos:related is an owl:SymmetricProperty (along with skos:relatedMatch, skos:closeMatch and skos:exactMatch) I think it should be shown (and added to the JSON) for both concepts that are linked by it.

See also #120.

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #123

### CODE REVIEW

**Review by sroertgen — APPROVED** [review]

**Comment by acka47** [comment]
@dr0i, please deploy alongside #119 .

**Comment by dr0i** [comment]
Deployed to test alongside #119 et al.

**Comment by acka47** [comment]
+1 Everything works as expected. @dr0i please deploy to production.

**Comment by dr0i** [comment]
Deployed to production, closing.

**Pull request closed without merging**
