### PR TITLE
add support for skos:example

### LINKED ISSUE #124: Support skos:example
Requirement by IBI for "Klassifikation für interdisziplinäre Forschungsfelder", sent by V.P. via email (to @acka47 & @sroertgen) today (2021-01-28).

### PR DESCRIPTION
**Pull request by sroertgen**
This fixes #124

### CODE REVIEW

**Review by literarymachine — APPROVED** [review]
+1

**Comment by acka47** [comment]
@droi, can you please deploy this to test alongside #119?

**Comment by dr0i** [comment]
Deployed alongside #119 to test.

**Comment by acka47** [comment]
1+ Looks good, see e.g. https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/portal.de.html. @dr0i this is ready to be deployed on production.

**Comment by dr0i** [comment]
Deployed to production, closing.

**Pull request closed without merging**
