### PR TITLE
Add skos:related links

### LINKED ISSUE #105: Support skos:related
See https://github.com/skohub-io/skohub-vocabs/issues/103#issuecomment-720641027

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #105

### CODE REVIEW

**Review by dr0i — APPROVED** [review]
Looks good to me.

**Comment by dr0i** [comment]
Deployed to test (with resolving a conflict from https://github.com/skohub-io/skohub-vocabs/pull/102).

**Comment by acka47** [comment]
I am losing overview over what's going on. It seems to me that we can close this PR as the changes are also part of #117 and it makes sense to review all of these together, right?

**Comment by acka47** [comment]
Closing this one and will continue review at #117 .

**Pull request closed without merging**
