### PR TITLE
Update Frontend

### LINKED ISSUE #201: Implement logo, font & colour changes in SkoHub Vocabs
The defeault design for a SkoHub Vocabs instance must be adjusted according to https://github.com/skohub-io/skohub.io/blob/master/skohub-branding-basics.pdf

### PR DESCRIPTION
**Pull request by kaimertens**
Logo, color-, font-changes.

Fixes #201

### CODE REVIEW

**Comment by sroertgen** [comment]
@kaimertens I made a first functional test and it looks good. Only thing I'm missing is the for me badge

image

will now have a deeper look

**Comment by kaimertens** [comment]
The fork-me badge can be found in the lower left corner. I had to simulate it. No idea why it doesn't appear. The CSS is included.

**Comment by kaimertens** [comment]
I completely replaced the old color variables with new ones. All colors can now be changed via the new variables.

These are the old variables:

base: 'rgb(242, 245, 247)',
blockBase: 'hsl(0, 100%, 100%)',
primary: 'hsl(0, 0%, 24%)',
inputBase: 'hsl(204, 24%, 96%)',
inputAction: 'hsl(192, 8.2%, 88%)',
accent: 'hsl(161.6, 71.8%, 41.8%)',
accentDark: 'hsl(161.6, 71.8%, 31.8%)',
text: 'rgb(15, 85, 75)',

**Comment by sroertgen** [comment]
> The fork-me badge can be found in the lower left corner. I had to simulate it. No idea why it doesn't appear. The CSS is included.

okay, I found out. The banner only shows up, when stuff is run via the webhook, because otherwise `GATSBY_RESPOSITORY_URL` is not set. 

If you set explicitly and run `GATSBY_RESPOSITORY_URL=www.google.com npm run develop` it shows up.

So looks good to me.

@acka47 what do you think?

**Comment by acka47** [comment]
I built test vocabs at https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/index.de.html.

I really lilke everything except for the "Fork this vocab banner. This is not optimal:

image

@sroertgen and me decided that we for now will use this solution: Put the link to the repo on the left side of the footer with the String "Source", e.g.:

[Source](https://github.com/acka47/testing-skohub-vocabs)

**Comment by acka47** [comment]
I also just noticed that "SkoHub-Vocabs" is written with a hyphen. It should be without: "SkoHub Vocabs" You copied correctly it from the last version. We have not been consistent there in the past but will try to be in the future. :-)

**Review by acka47 — APPROVED** [review]
+1 Looks fine

**Pull request merged**
