### PR TITLE
233 tests

### PR DESCRIPTION
**Pull request by sroertgen**
For a long time tests have not been written when new functionality was added. This is now changing.

I updated the test suite to now use https://testing-library.com/, because Enzyme is dead (https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl).

I added tests to test new funcationalities and components added since the last tests, e.g. Collections, Language Tags, display of the later added skos properties. But I also added some tests to already present components like `treeControls`, `nestedList` and a few others.

After that I added [cypress](https://docs.cypress.io/guides/overview/why-cypress) to build some e2e tests.

Cypress' e2e tests were also added to the GitHub Workflow to automate testing.

For future development I would like to migrate to a test driven development approach, so we start about thinking the desired behavior of the new feature, write tests for it and then start developing the feature.

To see the tests running use `npm run test`, to see test coverage run `npm run test:coverage` to run the e2e tests use `npm run test:e2e:ci` or `npm run test:e2e` to start the interactive test suite.

We use this three test files
- [test/data/hashURIConceptScheme.ttl](https://github.com/skohub-io/skohub-vocabs/blob/233-tests/test/data/hashURIConceptScheme.ttl) (one-lang, no-hierarchy, hashURI)
- [test/data/slashURIConceptScheme.ttl](https://github.com/skohub-io/skohub-vocabs/blob/233-tests/test/data/slashURIConceptScheme.ttl) (multi-lang, hierarchy, collection, slashURI)
- [test/data/interactivityType.ttl](https://github.com/skohub-io/skohub-vocabs/blob/233-tests/test/data/interactivityType.ttl) (one-lang, slashURI)

### CODE REVIEW

**Comment by sroertgen** [comment]
deployed to dev for testing

**Comment by sroertgen** [comment]
@acka47 see the first comment for the test files I created and please check if I missed something there

**Comment by acka47** [comment]
I am just trying this out an it looks very good. However, trying out the tests (in Firefox 108.0.2) I get a several errors.

Two timeout errors  (in index.cy.js and languageTags.cy.js):

grafik

grafik

Two 404 errors where it looks like the local URLs are not constructed correctly:

grafik

grafik

Am I doing something wrong?

**Comment by acka47** [comment]
> see the first comment for the test files I created and please check if I missed something there

This looks quite good, I only noticed one thing: The hash URI vocab is monolingual. We should probably also test a multilingual vocab there. (There are some real-world examples in https://github.com/hbz/lobid-vocabs (e.g. libtype.ttl), they do not have any hierarchy, though.)
-

**Comment by acka47** [comment]
> trying out the tests (in Firefox 108.0.2) I get a several errors.

FYI, I get the same errors when trying it out with Chromium 108.

**Comment by sroertgen** [comment]
> > trying out the tests (in Firefox 108.0.2) I get a several errors.
> 
> FYI, I get the same errors when trying it out with Chromium 108.

if you are using the cypress tests in interactive mode (`npm run test:e2e`) make sure you have set up the following things:

- the three test files are in your data folder
- you are running a development server with `npm run develop` (in a different terminal)

Is this the case and is it still throwing an error?

**Comment by acka47** [comment]
> the three test files are in your data folder

I did this.

> you are running a development server with npm run develop (in a different terminal)

When trying it out the first time, I got the feeling that this step is done automatically when triggering `npm run test:e2e`, isn't it? However, in this try, I started it myself in a different terminal.

Three tests are now running but index.cy.js still gives an error:

image


> I should maybe add this to the README as well

+1 Yes, for now I don't see any test documentaiton in the README but followed the insturctions in the original PR comment.

**Comment by acka47** [comment]
> When trying it out the first time, I got the feeling that this step is done automatically when triggering npm run test:e2e, isn't it?

I tried this out without running `npm run develop` (or `gatsby debvelop`, is it the same?) beforehand and it worked the same. (I also got the error described in the the former comment, though.)

**Comment by sroertgen** [comment]
Have you more than three vocabs in your data folder? Because the error says that it found 5 links.

**Comment by acka47** [comment]
I think, I found the reason for the error. I had too many files in the `data` folder.

>> the three test files are in your data folder
>
> I did this.

Actually, I only did cp test/data/*.ttl data` which led to four files being copied to the data folder. Is one of the vocabs in test/data not used for tests? I don't get it.

**Comment by acka47** [comment]
I will wait till you have cleaned this up (only ttl files in test/data that are used for tests and maybe some scripting for the tests to run plus adding the test doc to the README) and will then review again, ok?

**Comment by sroertgen** [comment]
Yes, only the three files:

[test/data/hashURIConceptScheme.ttl](https://github.com/skohub-io/skohub-vocabs/blob/233-tests/test/data/hashURIConceptScheme.ttl) (one-lang, no-hierarchy, hashURI)
    [test/data/slashURIConceptScheme.ttl](https://github.com/skohub-io/skohub-vocabs/blob/233-tests/test/data/slashURIConceptScheme.ttl) (multi-lang, hierarchy, collection, slashURI)
    [test/data/interactivityType.ttl](https://github.com/skohub-io/skohub-vocabs/blob/233-tests/test/data/interactivityType.ttl) (one-lang, slashURI)

are used for testing.

The systematik.ttl file is for demo purposes (we mention it in the README to test out SkoHub Vocabs)

**Comment by acka47** [comment]
> The systematik.ttl file is for demo purposes (we mention it in the README to test out SkoHub Vocabs)

I think we should either also use it for testing or remove it and replace it in the README with an actual test vocab

**Comment by acka47** [comment]
> I think we should either also use it for testing or remove it and replace it in the README with an actual test vocab

Another option would be to put it in another folder (`demo-data` or so).

**Comment by sroertgen** [comment]
I added a demo folder and documentation about conducting tests.

**Review by acka47 — APPROVED** [review]
Pushed some small changes to the README. +1

**Pull request merged**
