### PR TITLE
Remove code related to inbox, followers and jsonas

### LINKED ISSUE #171: Remove inboxes and ActivityStreams JSON
SkoHub PubSub (as well as SkoHub Editor) hasn't been used in production settings yet. Because of this and because of missing resources we'd need for maintenance, we decided to switch off both modules on skohub.io for an indefinite period. 

Against this background, we should better cleanly remove all PubSub related functions from SkoHub Vocabs, which are at least these:

- [x] `jsonas`, `inbox` and `followers` stuff in `gatsby-node.js`, `src/queries.js`, `/.env.example`, `src/common.js`, `/src/types.js`
- [x] inbox link in `/src/components/Concept.js`
- [x] inbox mention in `README.md`

### PR DESCRIPTION
**Pull request by solth**
This pull request removes code related to "inbox", "followers" and JSON activity streams from JavaScript, environment and README files. 

Fixes #171

### CODE REVIEW

**Comment by acka47** [comment]
I will do functional review and comment on the issue at #171. Assigning the PR to @sroertgen for code review.

**Comment by acka47** [comment]
I made my functional review and gave a +1, see https://github.com/skohub-io/skohub-vocabs/issues/171#issuecomment-1233816037.

**Review by sroertgen — CHANGES_REQUESTED** [review]
Looks good to me as well. 

The only additional leftovers I found are: 

https://github.com/skohub-io/skohub-vocabs/blob/e8595da2e4345ecab9f7709f376ef4cfbc0df435/static/.htaccess#L5

and 

https://github.com/skohub-io/skohub-vocabs/blob/6d2d032b170c121da94f1d346e66c8ee4bdef306/src/context.js#L11

I think these can be removed as well.

**Review by sroertgen — APPROVED** [review]

**Comment by sroertgen** [comment]
Good from my side! Thanks @solth 

@acka47 I assigned you to merge if you want.

**Comment by acka47** [comment]
@dr0i Please merge and deploy to production.

**Comment by dr0i** [comment]
Merged and deployed, closed.

**Pull request merged**
