### PR TITLE
255 in scheme array

### LINKED ISSUE #254: Two concept schemes in one file or one concept scheme across multiple files break build
Trying to parse the [NALT](https://agclass.nal.usda.gov/download-files) files in SkoHub Vocabs I noticed that the vocabulary does not build.

This seems to be, because the files contain two concept schemes and some tests with small vocabularies approved that.

Related to that I noticed that one concept scheme splitted into multiple files would also not build.

Since both is totally ok in RDF, SkoHub Vocabs should be able to parse these kind of files.

### PR DESCRIPTION
**Pull request by sroertgen**
This will resolve #254 and #255 

Now it is possible to have either one concept scheme in two files or two concept schemes in one file.

I added tests and test data to check this feature.

The biggest visible change in the front end was done in respect to show that one concept is present in multiple concept schemes. Because the concept always has the same URI regardless of the concept scheme I'm browsing we needed to display that somehow. This is now done by adding all concept schemes in the header and making the one active bold:

image

The `inScheme` information is also rendered on a concepts page.

### CODE REVIEW

**Comment by sroertgen** [comment]
Deployed to test with two test files, one having two schemes in one file, the other having one scheme split in two files.
Also there is one concept linked from two concept schemes: 

Vocabs: https://test.skohub.io/sroertgen/test-vocabs/heads/main/index.en.html
Concept present in two schemes: https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/two-concepts-one-file/c1.en.html

**Comment by sroertgen** [comment]
(This is by the way also a test to check if the separation of skohub vocabs und webhook work, since I merged these two branches in the background and thanks to @Phu2 this is already running on the test system)

**Comment by sroertgen** [comment]
Note to myself: If this is approved, we will merge into main and after that merge #244

**Comment by acka47** [comment]
Nearly everything looks and works fine but I suggest one change regarding the two vocabs in the header:

image

I think we should only show the main vocab that people are browsing there an only list the other under "In Scheme". Thus, we would have a setup that works the same when the second concept scheme a concept is part of is not published with SkoHub Vocabs or on another SkoHub instance. Or am I missing something?

**Review by acka47 — CHANGES_REQUESTED** [review]
See my comment re. the header for the requested changes.

**Comment by sroertgen** [comment]
@acka47 But which concept scheme should be chosen when a user directly visits a concept page? always the first found that is also published with skohub vocabs?

**Comment by Phu2** [comment]
Why should we display the concept scheme(s) in the header? They are present in the details section already. So i would remove them altogether from the header.

**Comment by sroertgen** [comment]
Yes, Adrian had the same objection.

I fixed it with https://github.com/skohub-io/skohub-vocabs/pull/259/commits/92c5c751c42210f15212da4185cd7dac70a810ac

**Comment by sroertgen** [comment]
@acka47 

Please have a look at https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/two-concepts-one-file/c1.en.html

I fixed the display of concept schemes in the header.

**Review by acka47 — APPROVED** [review]

**Review by Phu2 — APPROVED** [review]

**Pull request merged**
