### PR TITLE
206 language tags

### PR DESCRIPTION
**Pull request by sroertgen**
During working on the issue #206, I noticed some related issues that I want to address here:

## Possibility of jumping to a Concept Scheme that has no entry at all for the selected language

Currently it is possible to select a language and go to a concept scheme even though there is no single entry of that concept scheme in that language. This should be fixed by being directed to a concept scheme with defined languages.

## Concept Tree missing when changing language on a Collection page

When visiting a collection page directly (e.g. https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/test_collection.de.html) the concept tree is missing. This also happens when coming from a concept scheme. The concept tree is first there, but missing when changing the language. This should be fixed as well.

## Reduce built of pages to actually present languages

I noticed that currently pages are built for languages that they do not provide any label of. This happens because pages are built for all apparent languages in the turtle files regardless if the language is present in the respective concept scheme. This should be fixed by only building pages in languages that are also present in the respective concept scheme. 
I tested this with adding concept schemes in different languages one after another and got the following result:

old approach:
- 1 Concept Scheme with 1 language
  - total nodes 1276,
  - site page nodes 618
  - size of public folder: 29MB
- 2 concept schemes with each 1 having one language, but different ones
  - total nodes 3738
  - Site pages nodes 2464
  - size of public folder: 83MB
- 3 concept schemes with each 1 having one language, but different ones
  - total nodes 7340
  - Sitepage nodes 5540
  - size of public folder: 166MB

new approach:
- 1 Concept Scheme with 1 language
  - total nodes 1276
  - site page nodes 618
  - size of public folder: 29MB
- 2 concept schemes with each 1 having one language, but different ones
  - total nodes 2508
  - site page nodes 1234
  - size of public folder: 53MB
- 3 concept schemes with each 1 having one language, but different ones
  - total nodes 3740
  - site page nodes 1850
  - size of public folder: 78MB

## Only show languages present in a concept scheme

Being the original issue, this is also fixed.

### CODE REVIEW

**Comment by sroertgen** [comment]
@acka47 merged into dev for review

**Comment by acka47** [comment]
> Currently it is possible to select a language and go to a concept scheme even though there is no single entry of that concept scheme in that language. 

This is fixed.

> When visiting a collection page directly (e.g. https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/test_collection.de.html) the concept tree is missing.

This is **not** fixed: https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/test_collection.de.html

> This also happens when coming from a concept scheme. The concept tree is first there, but missing when changing the language. 

This is fixed.

> Reduce built of pages to actually present languages

Fixed. Compare https://skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/scheme.uk.html and https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/scheme.uk.html

> Only show languages present in a concept scheme

Also fixed.

**Comment by sroertgen** [comment]
> > When visiting a collection page directly (e.g. https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hcrt/test_collection.de.html) the concept tree is missing.
> 
> This does not work yet. If easy to fix, please do. Otherwise, please deploy anyway as this already improves the software a lot.

This should now be fixed.

Besides I noticed that the language selector also disappeared when switching language being on a concept page. This is also fixed.

**Comment by acka47** [comment]
+1 please deploy

**Pull request merged**
