### PR TITLE
284-other-attr-for-cs

### PR DESCRIPTION
**Pull request by sroertgen**
Added attributes as proposed in #284

### CODE REVIEW

**Comment by acka47** [comment]
I tried it with `dc:description` (as it is mentione din https://metadaten.community/t/lrmi-vokabulare-als-json-ld/59/3?u=acka47 that DC vocabs used it) which does not work. Please add this as well.

**Comment by acka47** [comment]
Although I have removed `dc:description` from `hcrt.ttl` it still won't build: https://test.skohub.io/build/?id=3e4fc380-6e5d-4137-b917-df2b7a82cb58

Is it because I use `dc:elements` with a URI? I don't know.

**Comment by acka47** [comment]
> Is it because I use `dc:elements` with a URI? I don't know.

No, this wasn't the problem, see https://test.skohub.io/build/?id=d824cf8f-d9d5-4dab-9659-0408aae249bf

It looks like there is a problem with the HCRT file at https://github.com/acka47/testing-skohub-vocabs/blob/master/hcrt.ttl. I just copied it over from the AMB org and added `dc:title` and `dc:creator`, so I guess this isn't working yet.

**Comment by sroertgen** [comment]
The error was that the SEO component did not receive the new title options and therefore could not build the `<meta>` elements in the `head`. I did not notice because that was not yet tested, but I added tests now.

I also added `dc:description` for describing the concept scheme.

Maybe just another thing to shortly discuss. How do you suggest the new attributes to be displayed in the JSON?
Currently it is:

```js
"dctitle": {
    "de": "Hochschulcampus Ressourcentypen",
    "en": "Higher Education Resource Types",
    "nl": "Brontypen voor het hoger onderwijs",
    "uk": "Типи ресурсів вищої освіти"
  },
  "dcdescription": {
    "de": "Eine Wertelliste für Typen von Lernressourcen (Learning Resource Type), entstanden im Kontext des Metadatenschemas \"LOM for Higher Education OER Repositories\" (https://w3id.org/dini-ag-kim/hs-oer-lom-profil/latest/)."
  }
```

and in the context:

```js
"dctitle": {
      "@id": "http://purl.org/dc/elements/1.1/title",
      "@container": "@language"
    },
    "dcdescription": {
      "@id": "http://purl.org/dc/elements/1.1/description",
      "@container": "@language"
    },
```

which is all valid, but we did not talk about it. Is this ok for you?

**Comment by acka47** [comment]
Now everything is working fine and we'll only have to update the context as discussed above.

**Comment by sroertgen** [comment]
@acka47 Implemented changes as requested.

**Comment by acka47** [comment]
The JSON looks good now but I encountered a problem with the HTML build. It is completing but the site does not work in the browser:

- Build log https://test.skohub.io/build/?id=66df181e-35a5-427e-846b-d54b9136caeb
- Built page that won't load: https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/

**Review by acka47 — CHANGES_REQUESTED** [review]
See comment

**Review by acka47 — APPROVED** [review]
After deleting my browser cache it worked as expected. +1

**Pull request merged**
