### PR TITLE
Add preliminary setup using Docker

### PR DESCRIPTION
**Pull request by Phu2**

### CODE REVIEW

**Comment by sroertgen** [comment]
This looks good already, I just noticed two issues:

1. The README should be adjusted on how to run development in docker.
2. I get some additional language tags "0" and "1"
image

I have no idea where this comes from. But it seems to disappear if one merges the current master into this branch.

**Review by sroertgen — CHANGES_REQUESTED** [review]
This looks good already, I just noticed two issues:

1. The README should be adjusted on how to run development in docker.
2. I get some additional language tags "0" and "1"
image

I have no idea where this comes from. But it seems to disappear if one merges the current master into this branch.

**Comment by Phu2** [comment]
I had to remove the `host` networking mode because it only works on Linux hosts as stated in the docs https://docs.docker.com/network/host/

**Comment by Phu2** [comment]
Couldn't reproduce these strange language tags "0" and "1"...

**Comment by Phu2** [comment]
@sroertgen Please have a look at my wording in the README regarding the development set up. Not sure if it is clear enough.

**Review by sroertgen — APPROVED** [review]

**Pull request merged**
