### PR TITLE
142 alt labels

### LINKED ISSUE #142: Show altLabel on concept page
Requested in https://github.com/skohub-io/skohub-vocabs/issues/128#issuecomment-857844413.

Currently, `altLabel` information is not shown in the HTML, see e.g. http://w3id.org/kim/schulfaecher/s1028 where you can find two altLabels in the JSON.

### PR DESCRIPTION
**Pull request by sroertgen**
I added altLabels to be displayed on a Concepts page as requested in #142.

This will close #142.

### CODE REVIEW

**Comment by acka47** [comment]
Looks good locally. However, as with the last PRs, I'd like to review this on the test system. For @dr0i to deploy this to test, the lst failing check needs to be fixed. Assigning @sroertgen to have a look at this.

**Comment by sroertgen** [comment]
checks have passed now. I just reran the tests. It failed the first time due to some network issues I guess.

**Comment by acka47** [comment]
@dr0i Please deploy to test.

**Comment by dr0i** [comment]
Deployed, but I can't see e.g. "Heimatunterricht" at https://test.skohub.io/dini-ag-kim/schulfaecher/heads/main/w3id.org/kim/schulfaecher/s1028.de.html, so probably it's not deployed correctly?

**Comment by acka47** [comment]
> Deployed, but I can't see e.g. "Heimatunterricht" at https://test.skohub.io/dini-ag-kim/schulfaecher/heads/main/w3id.org/kim/schulfaecher/s1028.de.html, so probably it's not deployed correctly?

A new build has to be triggered first and then we'll see whether it works.

**Comment by acka47** [comment]
+1 Looks good, see https://test.skohub.io/dini-ag-kim/schulfaecher/heads/skohubTest/w3id.org/kim/schulfaecher/s1028.de.html. Please deploy to production, @dr0i .

**Review by acka47 — APPROVED** [review]
+1

**Comment by dr0i** [comment]
Deployed to production, closed.
You may need to rebuild the vocabs at production then to show these alt labels?

**Comment by acka47** [comment]
>  You may need to rebuild the vocabs at production then to show these alt labels?

Yes

**Pull request merged**
