### PR TITLE
161 search by notation

### LINKED ISSUE #128: Add strings from skos:altLabel & skos:example to FlexSearch index
Requested by V.P. via email on 2021-02-21:

> Die Suchfunktion ist ein tolles Feature der 
> Visualisierung, die Suche sucht aber nur in den Klassenbezeichnungen und 
> nicht in den Scope Notes und Examples. Ist dies mit Absicht so gewählt 
> oder einfach schwieriger zu implementieren? Die Frage kam deshalb auf, 
> weil bei unserer Klassifikation das Szenario durchaus gesehen wird, dass 
> die Nutzenden ein Wort aus den Examples eingeben, um zu suchen, in 
> welcher Klasse dies ist.

It looks like that currently the FlexSearch index is only built from `skos:prefLabel` in all languages that are provided (although there seem to be some problems with this, see #127). The use case to find concepts via `altLabel` or `example` definitely makes sense to me.

### PR DESCRIPTION
**Pull request by sroertgen**
The labels from

- `skos:altLabel`
- `skos:notation`
- `skos:hiddenLabel`
- `skos:definition` 

are now indexed. By selection of the respective label, only the relevant index gets loaded. This means we don't have one blown up index, but multiple for each label, which makes us handle even quite large vocabs performant.
Also flexsearch has quite improved, so the index is not so big like before.

Re: Accessibility you are now able to check and uncheck boxes using `Alt + <first letter of label` e.g. `Alt + a` to toggle search for altLabels. `Ctrl + k` will you bring back to the search box.

Would like to know if the remaining labels i asked for in #128 should also be added. Since they will not blow up the index by default, I see no problem in doing so.

Will close #128 #161

### CODE REVIEW

**Comment by sroertgen** [comment]
The failing tests, I might handle in a separate issue. Everything goes through locally and I suspect some GitHub Action related issue, since sometimes one cypress test fails and sometimes two.

**Comment by sroertgen** [comment]
Assigning @acka47 for functional review

see e.g. https://test.skohub.io/sroertgen/test-vocabs/heads/main/index.en.html

but you can also push your on vocab to the test instance

**Comment by sroertgen** [comment]
@acka47 you can test now, e.g. https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/two-concepts-one-file/c1.de.html

or you can send your own vocab to the test-server

**Comment by sroertgen** [comment]
@acka47 please check again.
Attributes are not set in a modal.

**Comment by acka47** [comment]
This looks really good. One last UX thing: I find myself adjusting toggle buttons and then trying to click into the search window to start a search. This won't work at the moment and I have to go back to hit the "close" button first. There are two options for improvements:

1. Do not require to hit the "close" button and also close the window when you click anywhere else.
2. Remove the "close" button completely.

**Review by acka47 — CHANGES_REQUESTED** [review]
Please adjust the UX as commented

**Comment by sroertgen** [comment]
@acka47 Outside closing is now implemented.
Please check again, e.g. https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/two-concepts-one-file/c1.de.html

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
