### PR TITLE
add meaningful error message if data folder is empty

### LINKED ISSUE #212: Show meaningful error message if `data`-folder is empty
If there is no data in the data folder there is currently some cryptic error messages, which do not point to the cause of error, but give something like that:

```
Encountered an error parsing the provided GraphQL type definitions:
Syntax Error: Expected Name, found "}".

  37 |     hub: String
  38 |   }
  39 |
  40 |   type LanguageMap {
  41 |
> 42 |   }
     |   ^
  43 |
  44 |   type LanguageMapArray {
  45 |
  46 |   }
  47 |
```

### PR DESCRIPTION
**Pull request by sroertgen**
Adds a meaningful error message if the data folder is empty.

closes #212

### CODE REVIEW

**Comment by acka47** [comment]
This is meaningful and a huge improvement:

image

However, t would be even better if the message would be shown way down in the output. Currently, you have to scroll up a lot to see the message.

**Review by acka47 — APPROVED** [review]
+1 If the message could be moved to the button of the log it would be even better.

**Comment by sroertgen** [comment]
After some research I don't think this is possible and seems to be the desired behavior. 
If one reads the output from top to bottom one gets immediately notified about the last successful operation and when the error occurred. 
Reading from the bottom one gets hinted that one should check above for error messages.

**Comment by acka47** [comment]
Ok, so please deploy.

**Pull request merged**
