### PR TITLE
242 contributing guidelines

### PR DESCRIPTION
**Pull request by sroertgen**
This adds contributing guidelines for skohub development.

I suggest that after the PR is approved, we should open a repo for the contributing guidelines and link from all skohub modules to that repo.
This makes the guidelines easier to maintain.

### CODE REVIEW

**Comment by acka47** [comment]
@katauber https://github.com/skohub-io/skohub-vocabs/pull/262/commits/02bce1cfe138711a7dac0979668497107faf8bac is something that also needs to be done in the Metafacture Contributing.md. See also https://github.com/skohub-io/skohub-vocabs/issues/242#issuecomment-1443644808

**Comment by sroertgen** [comment]
CONTRIBUTING.md should at the end be hosted here: https://github.com/skohub-io/skohub.io

**Comment by katauber** [comment]
> @katauber FYI, [02bce1c](https://github.com/skohub-io/skohub-vocabs/commit/02bce1cfe138711a7dac0979668497107faf8bac) is something that also needs to be done in the Metafacture Contributing.md. See also [#242 (comment)](https://github.com/skohub-io/skohub-vocabs/issues/242#issuecomment-1443644808)

I would like to keep those lines for Metafacture Playground because these two things help understand the enhancement suggestion in detail. By describing which behaviour should be replaced and for which examples this behaviour is needed, the suggestion is specified in more detail.

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
