### PR TITLE
Add JSON-LD links

### LINKED ISSUE #111: Add link to JSON-LD for each page
Put a small  somewhere for each concept and scheme that links to the `.json` representatiob of each resource.

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #111

### CODE REVIEW

**Comment by acka47** [comment]
@dr0i, please deploy to test.

**Comment by dr0i** [comment]
Please resolve conflicts before deployment.

**Comment by acka47** [comment]
Conflicts are resolved. @dr0i, please deploy to test.

**Comment by dr0i** [comment]
Deployed to test.

**Comment by acka47** [comment]
I just build the test repo anew, see https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/scheme.de.html. Currently, the links are not pointing to the correct URL and I also suggest to put them in the top-right corner, maybe in a line above the heading. I will try to add a mockup on Monday.

**Comment by acka47** [comment]
This is where I would like to see the link, a little bit less prominent:

json-ld-link-mockup

**Comment by dr0i** [comment]
Assigning @sroertgen as reviewer, as discussed.
Also mind resolving conflicts.

**Comment by sroertgen** [comment]
@acka47 When we redeploy this branch on test, could you please tell me, where the link is pointing to and where it should point to? I could not reproduce this locally.

But I suggest testing #117 first. After this is ok, I can pull in `master` here. Pulling in `master` now to resolve conflicts would result in having these branches mixed up till `master` still has to be tested.

**Comment by acka47** [comment]
@sroertgen before deploying to test, conflicts have to be resolved.

**Comment by sroertgen** [comment]
@literarymachine resolved conflicts. we can now deploy to production so @acka47 might give a hint, where the link is pointing to and where it should point to.

**Comment by acka47** [comment]
@dr0i please deploy to test.

**Comment by dr0i** [comment]
Deployed to test.

**Comment by acka47** [comment]
@sroertgen See e.g. https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/diagram.de.html: the JSON-LD link points to https://test.skohub.io/w3id.org/kim/hcrt/diagram.json instead of https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/diagram.json.

**Comment by sroertgen** [comment]
Hey @acka47,

I changed the css and put the Json png in a dedicated component as we are using it in multiple places (Concept and ConceptScheme). I changed to Gatsby Link component. Let's see if this fixes the issue.

**Comment by acka47** [comment]
Please deploy to test, @dr0i .

**Comment by dr0i** [comment]
Deployed alongside #125 to test.

**Comment by acka47** [comment]
The linked URL looks good now, links are broken anyway, see e.g. https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/diagram.de.html. This looks like the same problem we encountered in https://github.com/skohub-io/skohub-vocabs/issues/79#issuecomment-720953716. @literarymachine resolved it by using HTML instead of Gatsby links, see https://github.com/skohub-io/skohub-vocabs/commit/2584e9b4c0dd067eb2aac0201f2941db1aba060b.

**Comment by sroertgen** [comment]
> @literarymachine resolved it by using HTML instead of Gatsby links, see [2584e9b](https://github.com/skohub-io/skohub-vocabs/commit/2584e9b4c0dd067eb2aac0201f2941db1aba060b).

Ok. I reversed to HTML link like originally in 011d88c3fb2060f21aac6ef555299150a46c6194.
Let's have another try.

**Comment by sroertgen** [comment]
I can't assign @literarymachine as reviewer ( I think because he opened the Pull Request). I think he still should have a look at the changes I made.

**Comment by acka47** [comment]
@dr0i Is 011d88c3fb2060f21aac6ef555299150a46c6194 deployed on test? The links are still broken so I think it the last commit wasn't deployed yet...

**Comment by dr0i** [comment]
@acka47 hm, 011d88c was deployed at 22. December last year.
You may mean fd73056 which wasn't deployed (see this ticket - it was commited after my test deployment at https://github.com/skohub-io/skohub-vocabs/pull/119#issuecomment-770668131).
I will do update and re-deploy now.

**Comment by dr0i** [comment]
Deployed to test.

**Comment by acka47** [comment]
The problem with the Gatsby links is gone but the URLs point to the wrong direction because the "GitHub bit" (in my test repo:`acka47/hcrt/heads/master`) is missing. See e.g. https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/diagram.de.html.

**Comment by sroertgen** [comment]
I just saw, now the link is broken again like here:

> @sroertgen See e.g. https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/diagram.de.html: the JSON-LD link points to https://test.skohub.io/w3id.org/kim/hcrt/diagram.json instead of https://test.skohub.io/acka47/hcrt/heads/master/w3id.org/kim/hcrt/diagram.json.

@literarymachine do you have an idea here? I guess the Gatsby Link thing is not working, because Gatsby is not building the `.json`-pages and therefore does not know them, so thinks they are not there. 
Not using the Gatsby Link component the path is not build correctly. Have you experienced this before?

**Comment by literarymachine** [comment]
I think the problem

**Comment by sroertgen** [comment]
@dr0i let's have another try.

@literarymachine `(process.env.BASEURL || '')` was somehow not picked up in the `src/components/JsonLink.js`-component. I got the value by passing the `BASEURL` from `gatsby-node.js` to `Concept.js` and `ConceptScheme.js` components. It was already defined to be passed in the `createPage` context (`gatsby-node.js`), but not picked up in the components.

**Comment by dr0i** [comment]
Deployed to test.

**Comment by acka47** [comment]
+1 The links are finally working! Please deploy to production, @dr0i .

**Comment by dr0i** [comment]
Deployed to production, closing.

**Pull request closed without merging**
